import { existsSync, readFileSync, statSync } from 'node:fs'
import { mkdtemp, rm } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { afterEach, beforeEach, describe, expect, it } from 'vitest'
import { defineComponent } from '../src/index.js'
import { DEFAULT_MANIFEST_PATH, generateManifestContent } from '../src/manifest.js'
import { presetVaria } from '../src/preset.js'

let testDir: string

beforeEach(async () => {
  testDir = await mkdtemp(join(tmpdir(), 'varia-manifest-'))
})
afterEach(async () => {
  await rm(testDir, { recursive: true, force: true })
})

describe('manifest emission via presetVaria', () => {
  it('writes manifest to a custom path with all class names from components', () => {
    const path = join(testDir, 'manifest.d.ts')
    const button = defineComponent('btn', {
      base: 'inline-block',
      variants: {
        c: { primary: 'bg-blue-600' },
        outline: 'border-2',
      },
    })

    presetVaria({ components: [button], manifest: { path } })

    const content = readFileSync(path, 'utf-8')
    expect(content).toContain("'btn'")
    expect(content).toContain("'btn-c-primary'")
    expect(content).toContain("'btn-outline'")
    expect(content).toContain('export type VariaClasses')
    expect(content).toContain('Auto-generated by varia')
  })

  it('does not write any file when manifest: false', () => {
    const path = join(testDir, 'should-not-exist.d.ts')

    presetVaria({
      components: [defineComponent('btn', { base: 'inline-block' })],
      manifest: false,
    })

    expect(existsSync(path)).toBe(false)
  })

  it('skips writing when content is unchanged (hash-compare)', async () => {
    const path = join(testDir, 'manifest.d.ts')
    const button = defineComponent('btn', { base: 'inline-block' })

    presetVaria({ components: [button], manifest: { path } })
    const firstMtime = statSync(path).mtimeMs

    await new Promise((r) => setTimeout(r, 20))

    presetVaria({ components: [button], manifest: { path } })
    const secondMtime = statSync(path).mtimeMs

    expect(secondMtime).toBe(firstMtime)
  })

  it('rewrites when content changes', async () => {
    const path = join(testDir, 'manifest.d.ts')

    presetVaria({
      components: [defineComponent('btn', { base: 'inline-block' })],
      manifest: { path },
    })
    const firstMtime = statSync(path).mtimeMs

    await new Promise((r) => setTimeout(r, 20))

    presetVaria({
      components: [defineComponent('btn', { base: 'block' }), defineComponent('alert', { base: 'p-4' })],
      manifest: { path },
    })
    const secondMtime = statSync(path).mtimeMs

    expect(secondMtime).toBeGreaterThan(firstMtime)
    const content = readFileSync(path, 'utf-8')
    expect(content).toContain("'alert'")
  })

  it('creates intermediate directories if they do not exist', () => {
    const path = join(testDir, 'nested', 'deeply', 'manifest.d.ts')

    presetVaria({
      components: [defineComponent('btn', { base: 'inline-block' })],
      manifest: { path },
    })

    expect(existsSync(path)).toBe(true)
  })

  it('exposes the default manifest path constant', () => {
    expect(DEFAULT_MANIFEST_PATH).toBe('node_modules/.varia/manifest.d.ts')
  })
})

describe('generateManifestContent', () => {
  it('produces a sorted, deduplicated union of class names', () => {
    const a = defineComponent('btn', {
      variants: { c: { primary: 'x', danger: 'y' } },
    })
    const b = defineComponent('alert', {
      base: 'p-4',
      variants: { c: { info: 'z' } },
    })

    const content = generateManifestContent([a, b])

    expect(content).toMatchSnapshot()
  })

  it('emits | never when no class names exist', () => {
    const content = generateManifestContent([])
    expect(content).toContain('| never')
  })
})
