import { existsSync, readFileSync } from 'node:fs'
import { execSync } from 'node:child_process'
import { mkdir, mkdtemp, rm, writeFile, cp } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { afterAll, beforeAll, describe, expect, it } from 'vitest'

describe('varia/types subpath stub', () => {
  it('built dist/types.d.mts re-exports from the manifest at the published-layout path', () => {
    const stub = readFileSync('dist/types.d.mts', 'utf-8')
    expect(stub).toContain("export type { VariaClasses } from '../../.varia/manifest.js'")
  })

  it('package.json exports map has ./types entry pointing at dist/types.d.mts', () => {
    const pkg = JSON.parse(readFileSync('package.json', 'utf-8'))
    expect(pkg.exports['./types']).toEqual({ types: './dist/types.d.mts' })
  })
})

describe('varia/types in a flat node_modules fixture (npm-style layout)', () => {
  let fixture: string

  beforeAll(async () => {
    fixture = await mkdtemp(join(tmpdir(), 'varia-types-flat-'))

    const variaDir = join(fixture, 'node_modules', 'varia')
    const manifestDir = join(fixture, 'node_modules', '.varia')

    await mkdir(variaDir, { recursive: true })
    await mkdir(manifestDir, { recursive: true })

    await cp('dist', join(variaDir, 'dist'), { recursive: true })
    await cp('package.json', join(variaDir, 'package.json'))

    await writeFile(
      join(manifestDir, 'manifest.d.ts'),
      `// Auto-generated by varia. Do not edit.\nexport type VariaClasses = 'btn' | 'btn-c-primary'\n`,
    )

    await writeFile(
      join(fixture, 'consumer.ts'),
      `import type { VariaClasses } from 'varia/types'\n` +
        `const valid: VariaClasses = 'btn-c-primary'\n` +
        `// @ts-expect-error — invalid class should fail typecheck\n` +
        `const invalid: VariaClasses = 'not-a-real-class'\n` +
        `export { valid, invalid }\n`,
    )

    await writeFile(
      join(fixture, 'tsconfig.json'),
      JSON.stringify(
        {
          compilerOptions: {
            target: 'ES2022',
            module: 'ESNext',
            moduleResolution: 'bundler',
            strict: true,
            noEmit: true,
            skipLibCheck: true,
            ignoreDeprecations: '6.0',
          },
          include: ['consumer.ts'],
        },
        null,
        2,
      ),
    )
  })

  afterAll(async () => {
    if (fixture) await rm(fixture, { recursive: true, force: true })
  })

  const tscPath = join(process.cwd(), 'node_modules', '.bin', 'tsc')
  const runFixtureTypecheck = () =>
    execSync(`${tscPath} --noEmit`, { cwd: fixture, stdio: 'pipe' })

  it('resolves varia/types and produces no type errors against a real manifest', () => {
    expect(runFixtureTypecheck).not.toThrow()
  })

  it('manifest update flows through: changing the manifest changes resolved type', async () => {
    const manifestPath = join(fixture, 'node_modules', '.varia', 'manifest.d.ts')
    await writeFile(
      manifestPath,
      `export type VariaClasses = 'card' | 'card-c-primary'\n`,
    )

    await writeFile(
      join(fixture, 'consumer.ts'),
      `import type { VariaClasses } from 'varia/types'\n` +
        `const valid: VariaClasses = 'card-c-primary'\n` +
        `export { valid }\n`,
    )

    expect(runFixtureTypecheck).not.toThrow()
  })
})
