import type { DefinedComponent } from './internal/types.js'
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname } from 'node:path'

export const DEFAULT_MANIFEST_PATH = 'node_modules/.varia/manifest.d.ts'

export function generateManifestContent(components: DefinedComponent[]): string {
  const allClassNames = new Set<string>()
  for (const component of components) {
    for (const className of component.manifest.classNames) {
      allClassNames.add(className)
    }
  }
  const sorted = [...allClassNames].sort()
  const union
    = sorted.length > 0 ? sorted.map(n => `  | '${n}'`).join('\n') : '  | never'

  return `// Auto-generated by varia. Do not edit.
// Lists every valid varia class name across registered components.

export type VariaClasses =
${union}
`
}

export function emitManifest(components: DefinedComponent[], path: string): void {
  const content = generateManifestContent(components)

  if (existsSync(path)) {
    const existing = readFileSync(path, 'utf-8')
    if (existing === content)
      return
  }

  mkdirSync(dirname(path), { recursive: true })
  writeFileSync(path, content, 'utf-8')
}
